// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
//   Consider using 'partial classes' to extend these types
//   Input: SentencePieceProto
// </auto-generated>

#region Designer generated code
#pragma warning disable CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
namespace Sentencepiece
{
	using System.CodeDom.Compiler;
	using System.Diagnostics.CodeAnalysis;

		[ExcludeFromCodeCoverage]
		[GeneratedCode(null, "")]
    [global::ProtoBuf.ProtoContract()]
    internal partial class SentencePieceText : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"text")]
        [global::System.ComponentModel.DefaultValue("")]
        public string Text
        {
            get => __pbn__Text ?? "";
            set => __pbn__Text = value;
        }
        public bool ShouldSerializeText() => __pbn__Text != null;
        public void ResetText() => __pbn__Text = null;
        private string __pbn__Text;

        [global::ProtoBuf.ProtoMember(2, Name = @"pieces")]
        public global::System.Collections.Generic.List<SentencePiece> Pieces { get; } = new global::System.Collections.Generic.List<SentencePiece>();

        [global::ProtoBuf.ProtoMember(3, Name = @"score")]
        public float Score
        {
            get => __pbn__Score.GetValueOrDefault();
            set => __pbn__Score = value;
        }
        public bool ShouldSerializeScore() => __pbn__Score != null;
        public void ResetScore() => __pbn__Score = null;
        private float? __pbn__Score;

        [global::ProtoBuf.ProtoContract()]
        public partial class SentencePiece : global::ProtoBuf.IExtensible
        {
            private global::ProtoBuf.IExtension __pbn__extensionData;
            global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
                => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

            [global::ProtoBuf.ProtoMember(1, Name = @"piece")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Piece
            {
                get => __pbn__Piece ?? "";
                set => __pbn__Piece = value;
            }
            public bool ShouldSerializePiece() => __pbn__Piece != null;
            public void ResetPiece() => __pbn__Piece = null;
            private string __pbn__Piece;

            [global::ProtoBuf.ProtoMember(2, Name = @"id")]
            public uint Id
            {
                get => __pbn__Id.GetValueOrDefault();
                set => __pbn__Id = value;
            }
            public bool ShouldSerializeId() => __pbn__Id != null;
            public void ResetId() => __pbn__Id = null;
            private uint? __pbn__Id;

            [global::ProtoBuf.ProtoMember(3, Name = @"surface")]
            [global::System.ComponentModel.DefaultValue("")]
            public string Surface
            {
                get => __pbn__Surface ?? "";
                set => __pbn__Surface = value;
            }
            public bool ShouldSerializeSurface() => __pbn__Surface != null;
            public void ResetSurface() => __pbn__Surface = null;
            private string __pbn__Surface;

            [global::ProtoBuf.ProtoMember(4, Name = @"begin")]
            public uint Begin
            {
                get => __pbn__Begin.GetValueOrDefault();
                set => __pbn__Begin = value;
            }
            public bool ShouldSerializeBegin() => __pbn__Begin != null;
            public void ResetBegin() => __pbn__Begin = null;
            private uint? __pbn__Begin;

            [global::ProtoBuf.ProtoMember(5, Name = @"end")]
            public uint End
            {
                get => __pbn__End.GetValueOrDefault();
                set => __pbn__End = value;
            }
            public bool ShouldSerializeEnd() => __pbn__End != null;
            public void ResetEnd() => __pbn__End = null;
            private uint? __pbn__End;

        }

    }

    [ExcludeFromCodeCoverage]
    [GeneratedCode(null, "")]
    [global::ProtoBuf.ProtoContract()]
    internal partial class NBestSentencePieceText : global::ProtoBuf.IExtensible
    {
        private global::ProtoBuf.IExtension __pbn__extensionData;
        global::ProtoBuf.IExtension global::ProtoBuf.IExtensible.GetExtensionObject(bool createIfMissing)
            => global::ProtoBuf.Extensible.GetExtensionObject(ref __pbn__extensionData, createIfMissing);

        [global::ProtoBuf.ProtoMember(1, Name = @"nbests")]
        public global::System.Collections.Generic.List<SentencePieceText> Nbests { get; } = new global::System.Collections.Generic.List<SentencePieceText>();

    }

}

#pragma warning restore CS0612, CS0618, CS1591, CS3021, IDE0079, IDE1006, RCS1036, RCS1057, RCS1085, RCS1192
#endregion
