// <auto-generated>
//   This file was generated by a tool; you should avoid making direct changes.
// </auto-generated>

namespace GeoInfo.Iso4217;
#region Designer generated code
public enum Currency {
///<summary>Not a currency.</summary>
NotACurrency=-1,
///<summary>Not a currency, but instead an uninitialized variable.</summary>
Uninitialized=0,
/// <summary>
/// <para>Afghani</para>
/// </summary>
/// <value>id=AFN, numeric=971</value>
Afghani=26_945,
/// <summary>
/// <para>Euro</para>
/// </summary>
/// <value>id=EUR, numeric=978</value>
Euro=36_105,
/// <summary>
/// <para>Lek</para>
/// </summary>
/// <value>id=ALL, numeric=8</value>
Lek=23_233,
/// <summary>
/// <para>Algerian Dinar</para>
/// </summary>
/// <value>id=DZD, numeric=12</value>
AlgerianDinar=7_751,
/// <summary>
/// <para>US Dollar</para>
/// </summary>
/// <value>id=USD, numeric=840</value>
USDollar=7_337,
/// <summary>
/// <para>Kwanza</para>
/// </summary>
/// <value>id=AOA, numeric=973</value>
Kwanza=897,
/// <summary>
/// <para>East Caribbean Dollar</para>
/// </summary>
/// <value>id=XCD, numeric=951</value>
EastCaribbeanDollar=6_319,
/// <summary>
/// <para>Argentine Peso</para>
/// </summary>
/// <value>id=ARS, numeric=32</value>
ArgentinePeso=37_953,
/// <summary>
/// <para>Armenian Dram</para>
/// </summary>
/// <value>id=AMD, numeric=51</value>
ArmenianDram=6_913,
/// <summary>
/// <para>Aruban Florin</para>
/// </summary>
/// <value>id=AWG, numeric=533</value>
ArubanFlorin=13_697,
/// <summary>
/// <para>Australian Dollar</para>
/// </summary>
/// <value>id=AUD, numeric=36</value>
AustralianDollar=7_425,
/// <summary>
/// <para>Azerbaijan Manat</para>
/// </summary>
/// <value>id=AZN, numeric=944</value>
AzerbaijanManat=28_225,
/// <summary>
/// <para>Bahamian Dollar</para>
/// </summary>
/// <value>id=BSD, numeric=44</value>
BahamianDollar=7_299,
/// <summary>
/// <para>Bahraini Dinar</para>
/// </summary>
/// <value>id=BHD, numeric=48</value>
BahrainiDinar=6_595,
/// <summary>
/// <para>Taka</para>
/// </summary>
/// <value>id=BDT, numeric=50</value>
Taka=39_107,
/// <summary>
/// <para>Barbados Dollar</para>
/// </summary>
/// <value>id=BBD, numeric=52</value>
BarbadosDollar=6_211,
/// <summary>
/// <para>Belarusian Ruble</para>
/// </summary>
/// <value>id=BYN, numeric=933</value>
BelarusianRuble=28_163,
/// <summary>
/// <para>Belize Dollar</para>
/// </summary>
/// <value>id=BZD, numeric=84</value>
BelizeDollar=7_747,
/// <summary>
/// <para>CFA Franc BCEAO</para>
/// </summary>
/// <value>id=XOF, numeric=952</value>
CFAFrancBCEAO=11_183,
/// <summary>
/// <para>Bermudian Dollar</para>
/// </summary>
/// <value>id=BMD, numeric=60</value>
BermudianDollar=6_915,
/// <summary>
/// <para>Indian Rupee</para>
/// </summary>
/// <value>id=INR, numeric=356</value>
IndianRupee=35_665,
/// <summary>
/// <para>Ngultrum</para>
/// </summary>
/// <value>id=BTN, numeric=64</value>
Ngultrum=27_843,
/// <summary>
/// <para>Boliviano</para>
/// </summary>
/// <value>id=BOB, numeric=68</value>
Boliviano=2_947,
/// <summary>
/// <para>Mvdol</para>
/// </summary>
/// <value>id=BOV, numeric=984</value>
Mvdol=43_907,
/// <summary>
/// <para>Convertible Mark</para>
/// </summary>
/// <value>id=BAM, numeric=977</value>
ConvertibleMark=24_579,
/// <summary>
/// <para>Pula</para>
/// </summary>
/// <value>id=BWP, numeric=72</value>
Pula=32_131,
/// <summary>
/// <para>Norwegian Krone</para>
/// </summary>
/// <value>id=NOK, numeric=578</value>
NorwegianKrone=21_403,
/// <summary>
/// <para>Brazilian Real</para>
/// </summary>
/// <value>id=BRL, numeric=986</value>
BrazilianReal=23_619,
/// <summary>
/// <para>Brunei Dollar</para>
/// </summary>
/// <value>id=BND, numeric=96</value>
BruneiDollar=6_979,
/// <summary>
/// <para>Bulgarian Lev</para>
/// </summary>
/// <value>id=BGN, numeric=975</value>
BulgarianLev=27_011,
/// <summary>
/// <para>Burundi Franc</para>
/// </summary>
/// <value>id=BIF, numeric=108</value>
BurundiFranc=10_755,
/// <summary>
/// <para>Cabo Verde Escudo</para>
/// </summary>
/// <value>id=CVE, numeric=132</value>
CaboVerdeEscudo=9_541,
/// <summary>
/// <para>Riel</para>
/// </summary>
/// <value>id=KHR, numeric=116</value>
Riel=35_285,
/// <summary>
/// <para>CFA Franc BEAC</para>
/// </summary>
/// <value>id=XAF, numeric=950</value>
CFAFrancBEAC=10_287,
/// <summary>
/// <para>Canadian Dollar</para>
/// </summary>
/// <value>id=CAD, numeric=124</value>
CanadianDollar=6_149,
/// <summary>
/// <para>Cayman Islands Dollar</para>
/// </summary>
/// <value>id=KYD, numeric=136</value>
CaymanIslandsDollar=7_701,
/// <summary>
/// <para>Chilean Peso</para>
/// </summary>
/// <value>id=CLP, numeric=152</value>
ChileanPeso=31_429,
/// <summary>
/// <para>Unidad de Fomento</para>
/// </summary>
/// <value>id=CLF, numeric=990</value>
UnidaddeFomento=10_949,
/// <summary>
/// <para>Yuan Renminbi</para>
/// </summary>
/// <value>id=CNY, numeric=156</value>
YuanRenminbi=49_989,
/// <summary>
/// <para>Colombian Peso</para>
/// </summary>
/// <value>id=COP, numeric=170</value>
ColombianPeso=31_621,
/// <summary>
/// <para>Unidad de Valor Real</para>
/// </summary>
/// <value>id=COU, numeric=970</value>
UnidaddeValorReal=41_861,
/// <summary>
/// <para>Comorian Franc </para>
/// </summary>
/// <value>id=KMF, numeric=174</value>
ComorianFranc=11_029,
/// <summary>
/// <para>Congolese Franc</para>
/// </summary>
/// <value>id=CDF, numeric=976</value>
CongoleseFranc=10_437,
/// <summary>
/// <para>New Zealand Dollar</para>
/// </summary>
/// <value>id=NZD, numeric=554</value>
NewZealandDollar=7_771,
/// <summary>
/// <para>Costa Rican Colon</para>
/// </summary>
/// <value>id=CRC, numeric=188</value>
CostaRicanColon=5_189,
/// <summary>
/// <para>Cuban Peso</para>
/// </summary>
/// <value>id=CUP, numeric=192</value>
CubanPeso=32_005,
/// <summary>
/// <para>Peso Convertible</para>
/// </summary>
/// <value>id=CUC, numeric=931</value>
PesoConvertible=5_381,
/// <summary>
/// <para>Netherlands Antillean Guilder</para>
/// </summary>
/// <value>id=ANG, numeric=532</value>
NetherlandsAntilleanGuilder=13_121,
/// <summary>
/// <para>Czech Koruna</para>
/// </summary>
/// <value>id=CZK, numeric=203</value>
CzechKoruna=22_085,
/// <summary>
/// <para>Danish Krone</para>
/// </summary>
/// <value>id=DKK, numeric=208</value>
DanishKrone=21_127,
/// <summary>
/// <para>Djibouti Franc</para>
/// </summary>
/// <value>id=DJF, numeric=262</value>
DjiboutiFranc=10_823,
/// <summary>
/// <para>Dominican Peso</para>
/// </summary>
/// <value>id=DOP, numeric=214</value>
DominicanPeso=31_623,
/// <summary>
/// <para>Egyptian Pound</para>
/// </summary>
/// <value>id=EGP, numeric=818</value>
EgyptianPound=31_113,
/// <summary>
/// <para>El Salvador Colon</para>
/// </summary>
/// <value>id=SVC, numeric=222</value>
ElSalvadorColon=5_477,
/// <summary>
/// <para>Nakfa</para>
/// </summary>
/// <value>id=ERN, numeric=232</value>
Nakfa=27_721,
/// <summary>
/// <para>Lilangeni</para>
/// </summary>
/// <value>id=SZL, numeric=748</value>
Lilangeni=24_165,
/// <summary>
/// <para>Ethiopian Birr</para>
/// </summary>
/// <value>id=ETB, numeric=230</value>
EthiopianBirr=3_273,
/// <summary>
/// <para>Falkland Islands Pound</para>
/// </summary>
/// <value>id=FKP, numeric=238</value>
FalklandIslandsPound=31_371,
/// <summary>
/// <para>Fiji Dollar</para>
/// </summary>
/// <value>id=FJD, numeric=242</value>
FijiDollar=6_731,
/// <summary>
/// <para>CFP Franc</para>
/// </summary>
/// <value>id=XPF, numeric=953</value>
CFPFranc=11_247,
/// <summary>
/// <para>Dalasi</para>
/// </summary>
/// <value>id=GMD, numeric=270</value>
Dalasi=6_925,
/// <summary>
/// <para>Lari</para>
/// </summary>
/// <value>id=GEL, numeric=981</value>
Lari=22_797,
/// <summary>
/// <para>Ghana Cedi</para>
/// </summary>
/// <value>id=GHS, numeric=936</value>
GhanaCedi=37_325,
/// <summary>
/// <para>Gibraltar Pound</para>
/// </summary>
/// <value>id=GIP, numeric=292</value>
GibraltarPound=31_245,
/// <summary>
/// <para>Quetzal</para>
/// </summary>
/// <value>id=GTQ, numeric=320</value>
Quetzal=33_997,
/// <summary>
/// <para>Pound Sterling</para>
/// </summary>
/// <value>id=GBP, numeric=826</value>
PoundSterling=30_797,
/// <summary>
/// <para>Guinean Franc</para>
/// </summary>
/// <value>id=GNF, numeric=324</value>
GuineanFranc=11_085,
/// <summary>
/// <para>Guyana Dollar</para>
/// </summary>
/// <value>id=GYD, numeric=328</value>
GuyanaDollar=7_693,
/// <summary>
/// <para>Gourde</para>
/// </summary>
/// <value>id=HTG, numeric=332</value>
Gourde=13_519,
/// <summary>
/// <para>Lempira</para>
/// </summary>
/// <value>id=HNL, numeric=340</value>
Lempira=23_375,
/// <summary>
/// <para>Hong Kong Dollar</para>
/// </summary>
/// <value>id=HKD, numeric=344</value>
HongKongDollar=6_799,
/// <summary>
/// <para>Forint</para>
/// </summary>
/// <value>id=HUF, numeric=348</value>
Forint=11_535,
/// <summary>
/// <para>Iceland Krona</para>
/// </summary>
/// <value>id=ISK, numeric=352</value>
IcelandKrona=21_649,
/// <summary>
/// <para>Rupiah</para>
/// </summary>
/// <value>id=IDR, numeric=360</value>
Rupiah=35_025,
/// <summary>
/// <para>Iranian Rial</para>
/// </summary>
/// <value>id=IRR, numeric=364</value>
IranianRial=35_921,
/// <summary>
/// <para>Iraqi Dinar</para>
/// </summary>
/// <value>id=IQD, numeric=368</value>
IraqiDinar=7_185,
/// <summary>
/// <para>New Israeli Sheqel</para>
/// </summary>
/// <value>id=ILS, numeric=376</value>
NewIsraeliSheqel=37_585,
/// <summary>
/// <para>Jamaican Dollar</para>
/// </summary>
/// <value>id=JMD, numeric=388</value>
JamaicanDollar=6_931,
/// <summary>
/// <para>Yen</para>
/// </summary>
/// <value>id=JPY, numeric=392</value>
Yen=50_131,
/// <summary>
/// <para>Jordanian Dinar</para>
/// </summary>
/// <value>id=JOD, numeric=400</value>
JordanianDinar=7_059,
/// <summary>
/// <para>Tenge</para>
/// </summary>
/// <value>id=KZT, numeric=398</value>
Tenge=40_533,
/// <summary>
/// <para>Kenyan Shilling</para>
/// </summary>
/// <value>id=KES, numeric=404</value>
KenyanShilling=37_141,
/// <summary>
/// <para>North Korean Won</para>
/// </summary>
/// <value>id=KPW, numeric=408</value>
NorthKoreanWon=46_037,
/// <summary>
/// <para>Won</para>
/// </summary>
/// <value>id=KRW, numeric=410</value>
Won=46_165,
/// <summary>
/// <para>Kuwaiti Dinar</para>
/// </summary>
/// <value>id=KWD, numeric=414</value>
KuwaitiDinar=7_573,
/// <summary>
/// <para>Som</para>
/// </summary>
/// <value>id=KGS, numeric=417</value>
Som=37_269,
/// <summary>
/// <para>Lao Kip</para>
/// </summary>
/// <value>id=LAK, numeric=418</value>
LaoKip=20_503,
/// <summary>
/// <para>Lebanese Pound</para>
/// </summary>
/// <value>id=LBP, numeric=422</value>
LebanesePound=30_807,
/// <summary>
/// <para>Loti</para>
/// </summary>
/// <value>id=LSL, numeric=426</value>
Loti=23_703,
/// <summary>
/// <para>Rand</para>
/// </summary>
/// <value>id=ZAR, numeric=710</value>
Rand=34_867,
/// <summary>
/// <para>Liberian Dollar</para>
/// </summary>
/// <value>id=LRD, numeric=430</value>
LiberianDollar=7_255,
/// <summary>
/// <para>Libyan Dinar</para>
/// </summary>
/// <value>id=LYD, numeric=434</value>
LibyanDinar=7_703,
/// <summary>
/// <para>Swiss Franc</para>
/// </summary>
/// <value>id=CHF, numeric=756</value>
SwissFranc=10_693,
/// <summary>
/// <para>Pataca</para>
/// </summary>
/// <value>id=MOP, numeric=446</value>
Pataca=31_641,
/// <summary>
/// <para>Denar</para>
/// </summary>
/// <value>id=MKD, numeric=807</value>
Denar=6_809,
/// <summary>
/// <para>Malagasy Ariary</para>
/// </summary>
/// <value>id=MGA, numeric=969</value>
MalagasyAriary=409,
/// <summary>
/// <para>Malawi Kwacha</para>
/// </summary>
/// <value>id=MWK, numeric=454</value>
MalawiKwacha=21_913,
/// <summary>
/// <para>Malaysian Ringgit</para>
/// </summary>
/// <value>id=MYR, numeric=458</value>
MalaysianRinggit=36_377,
/// <summary>
/// <para>Rufiyaa</para>
/// </summary>
/// <value>id=MVR, numeric=462</value>
Rufiyaa=36_185,
/// <summary>
/// <para>Ouguiya</para>
/// </summary>
/// <value>id=MRU, numeric=929</value>
Ouguiya=42_073,
/// <summary>
/// <para>Mauritius Rupee</para>
/// </summary>
/// <value>id=MUR, numeric=480</value>
MauritiusRupee=36_121,
/// <summary>
/// <para>Mexican Peso</para>
/// </summary>
/// <value>id=MXN, numeric=484</value>
MexicanPeso=28_121,
/// <summary>
/// <para>Mexican Unidad de Inversion (UDI)</para>
/// </summary>
/// <value>id=MXV, numeric=979</value>
MexicanUnidaddeInversion=44_505,
/// <summary>
/// <para>Moldovan Leu</para>
/// </summary>
/// <value>id=MDL, numeric=498</value>
MoldovanLeu=22_745,
/// <summary>
/// <para>Tugrik</para>
/// </summary>
/// <value>id=MNT, numeric=496</value>
Tugrik=39_769,
/// <summary>
/// <para>Moroccan Dirham</para>
/// </summary>
/// <value>id=MAD, numeric=504</value>
MoroccanDirham=6_169,
/// <summary>
/// <para>Mozambique Metical</para>
/// </summary>
/// <value>id=MZN, numeric=943</value>
MozambiqueMetical=28_249,
/// <summary>
/// <para>Kyat</para>
/// </summary>
/// <value>id=MMK, numeric=104</value>
Kyat=21_273,
/// <summary>
/// <para>Namibia Dollar</para>
/// </summary>
/// <value>id=NAD, numeric=516</value>
NamibiaDollar=6_171,
/// <summary>
/// <para>Nepalese Rupee</para>
/// </summary>
/// <value>id=NPR, numeric=524</value>
NepaleseRupee=35_803,
/// <summary>
/// <para>Cordoba Oro</para>
/// </summary>
/// <value>id=NIO, numeric=558</value>
CordobaOro=29_211,
/// <summary>
/// <para>Naira</para>
/// </summary>
/// <value>id=NGN, numeric=566</value>
Naira=27_035,
/// <summary>
/// <para>Rial Omani</para>
/// </summary>
/// <value>id=OMR, numeric=512</value>
RialOmani=35_613,
/// <summary>
/// <para>Pakistan Rupee</para>
/// </summary>
/// <value>id=PKR, numeric=586</value>
PakistanRupee=35_487,
/// <summary>
/// <para>Balboa</para>
/// </summary>
/// <value>id=PAB, numeric=590</value>
Balboa=2_079,
/// <summary>
/// <para>Kina</para>
/// </summary>
/// <value>id=PGK, numeric=598</value>
Kina=20_895,
/// <summary>
/// <para>Guarani</para>
/// </summary>
/// <value>id=PYG, numeric=600</value>
Guarani=13_855,
/// <summary>
/// <para>Sol</para>
/// </summary>
/// <value>id=PEN, numeric=604</value>
Sol=26_911,
/// <summary>
/// <para>Philippine Peso</para>
/// </summary>
/// <value>id=PHP, numeric=608</value>
PhilippinePeso=31_199,
/// <summary>
/// <para>Zloty</para>
/// </summary>
/// <value>id=PLN, numeric=985</value>
Zloty=27_359,
/// <summary>
/// <para>Qatari Rial</para>
/// </summary>
/// <value>id=QAR, numeric=634</value>
QatariRial=34_849,
/// <summary>
/// <para>Romanian Leu</para>
/// </summary>
/// <value>id=RON, numeric=946</value>
RomanianLeu=27_555,
/// <summary>
/// <para>Russian Ruble</para>
/// </summary>
/// <value>id=RUB, numeric=643</value>
RussianRuble=3_363,
/// <summary>
/// <para>Rwanda Franc</para>
/// </summary>
/// <value>id=RWF, numeric=646</value>
RwandaFranc=11_683,
/// <summary>
/// <para>Saint Helena Pound</para>
/// </summary>
/// <value>id=SHP, numeric=654</value>
SaintHelenaPound=31_205,
/// <summary>
/// <para>Tala</para>
/// </summary>
/// <value>id=WST, numeric=882</value>
Tala=40_109,
/// <summary>
/// <para>Dobra</para>
/// </summary>
/// <value>id=STN, numeric=930</value>
Dobra=27_877,
/// <summary>
/// <para>Saudi Riyal</para>
/// </summary>
/// <value>id=SAR, numeric=682</value>
SaudiRiyal=34_853,
/// <summary>
/// <para>Serbian Dinar</para>
/// </summary>
/// <value>id=RSD, numeric=941</value>
SerbianDinar=7_331,
/// <summary>
/// <para>Seychelles Rupee</para>
/// </summary>
/// <value>id=SCR, numeric=690</value>
SeychellesRupee=34_981,
/// <summary>
/// <para>Leone</para>
/// </summary>
/// <value>id=SLE, numeric=925</value>
Leone=8_933,
/// <summary>
/// <para>Singapore Dollar</para>
/// </summary>
/// <value>id=SGD, numeric=702</value>
SingaporeDollar=6_565,
/// <summary>
/// <para>Sucre</para>
/// </summary>
/// <value>id=XSU, numeric=994</value>
Sucre=42_159,
/// <summary>
/// <para>Solomon Islands Dollar</para>
/// </summary>
/// <value>id=SBD, numeric=90</value>
SolomonIslandsDollar=6_245,
/// <summary>
/// <para>Somali Shilling</para>
/// </summary>
/// <value>id=SOS, numeric=706</value>
SomaliShilling=37_797,
/// <summary>
/// <para>South Sudanese Pound</para>
/// </summary>
/// <value>id=SSP, numeric=728</value>
SouthSudanesePound=31_909,
/// <summary>
/// <para>Sri Lanka Rupee</para>
/// </summary>
/// <value>id=LKR, numeric=144</value>
SriLankaRupee=35_479,
/// <summary>
/// <para>Sudanese Pound</para>
/// </summary>
/// <value>id=SDG, numeric=938</value>
SudanesePound=12_517,
/// <summary>
/// <para>Surinam Dollar</para>
/// </summary>
/// <value>id=SRD, numeric=968</value>
SurinamDollar=7_269,
/// <summary>
/// <para>Swedish Krona</para>
/// </summary>
/// <value>id=SEK, numeric=752</value>
SwedishKrona=20_773,
/// <summary>
/// <para>WIR Euro</para>
/// </summary>
/// <value>id=CHE, numeric=947</value>
WIREuro=8_645,
/// <summary>
/// <para>WIR Franc</para>
/// </summary>
/// <value>id=CHW, numeric=948</value>
WIRFranc=45_509,
/// <summary>
/// <para>Syrian Pound</para>
/// </summary>
/// <value>id=SYP, numeric=760</value>
SyrianPound=32_293,
/// <summary>
/// <para>New Taiwan Dollar</para>
/// </summary>
/// <value>id=TWD, numeric=901</value>
NewTaiwanDollar=7_591,
/// <summary>
/// <para>Somoni</para>
/// </summary>
/// <value>id=TJS, numeric=972</value>
Somoni=37_479,
/// <summary>
/// <para>Tanzanian Shilling</para>
/// </summary>
/// <value>id=TZS, numeric=834</value>
TanzanianShilling=38_503,
/// <summary>
/// <para>Baht</para>
/// </summary>
/// <value>id=THB, numeric=764</value>
Baht=2_535,
/// <summary>
/// <para>Pa’anga</para>
/// </summary>
/// <value>id=TOP, numeric=776</value>
Paanga=31_655,
/// <summary>
/// <para>Trinidad and Tobago Dollar</para>
/// </summary>
/// <value>id=TTD, numeric=780</value>
TrinidadandTobagoDollar=7_399,
/// <summary>
/// <para>Tunisian Dinar</para>
/// </summary>
/// <value>id=TND, numeric=788</value>
TunisianDinar=7_015,
/// <summary>
/// <para>Turkish Lira</para>
/// </summary>
/// <value>id=TRY, numeric=949</value>
TurkishLira=50_279,
/// <summary>
/// <para>Turkmenistan New Manat</para>
/// </summary>
/// <value>id=TMT, numeric=934</value>
TurkmenistanNewManat=39_719,
/// <summary>
/// <para>Uganda Shilling</para>
/// </summary>
/// <value>id=UGX, numeric=800</value>
UgandaShilling=47_529,
/// <summary>
/// <para>Hryvnia</para>
/// </summary>
/// <value>id=UAH, numeric=980</value>
Hryvnia=14_377,
/// <summary>
/// <para>UAE Dirham</para>
/// </summary>
/// <value>id=AED, numeric=784</value>
UAEDirham=6_401,
/// <summary>
/// <para>Peso Uruguayo</para>
/// </summary>
/// <value>id=UYU, numeric=858</value>
PesoUruguayo=42_537,
/// <summary>
/// <para>Uruguay Peso en Unidades Indexadas (UI)</para>
/// </summary>
/// <value>id=UYI, numeric=940</value>
UruguayPesoenUnidadesIndexadas=17_961,
/// <summary>
/// <para>Unidad Previsional</para>
/// </summary>
/// <value>id=UYW, numeric=927</value>
UnidadPrevisional=46_633,
/// <summary>
/// <para>Uzbekistan Sum</para>
/// </summary>
/// <value>id=UZS, numeric=860</value>
UzbekistanSum=38_505,
/// <summary>
/// <para>Vatu</para>
/// </summary>
/// <value>id=VUV, numeric=548</value>
Vatu=44_331,
/// <summary>
/// <para>Bolívar Soberano</para>
/// </summary>
/// <value>id=VES, numeric=928</value>
BolivarSoberano_VES=37_163,
/// <summary>
/// <para>Bolívar Soberano</para>
/// </summary>
/// <value>id=VED, numeric=926</value>
BolivarSoberano_VED=6_443,
/// <summary>
/// <para>Dong</para>
/// </summary>
/// <value>id=VND, numeric=704</value>
Dong=7_019,
/// <summary>
/// <para>Yemeni Rial</para>
/// </summary>
/// <value>id=YER, numeric=886</value>
YemeniRial=35_121,
/// <summary>
/// <para>Zambian Kwacha</para>
/// </summary>
/// <value>id=ZMW, numeric=967</value>
ZambianKwacha=45_875,
/// <summary>
/// <para>Zimbabwe Gold</para>
/// </summary>
/// <value>id=ZWG, numeric=924</value>
ZimbabweGold=13_747,
/// <summary>
/// <para>Codes specifically reserved for testing purposes</para>
/// </summary>
/// <value>id=XTS, numeric=963</value>
TestCurrency=38_127,
/// <summary>
/// <para>The codes assigned for transactions where no currency is involved</para>
/// </summary>
/// <value>id=XXX, numeric=999</value>
NoCurrencyInvolved=48_623,
/// <summary>
/// <para>Gold</para>
/// </summary>
/// <value>id=XAU, numeric=959</value>
Gold=41_007,
/// <summary>
/// <para>Palladium</para>
/// </summary>
/// <value>id=XPD, numeric=964</value>
Palladium=7_151,
/// <summary>
/// <para>Platinum</para>
/// </summary>
/// <value>id=XPT, numeric=962</value>
Platinum=39_919,
/// <summary>
/// <para>Silver</para>
/// </summary>
/// <value>id=XAG, numeric=961</value>
Silver=12_335,
}
#endregion
